//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakarRally.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malfunction
    {
        public int RaceId { get; set; }
        public int VehicleId { get; set; }
        public int MalfunctionId { get; set; }
        public short Status { get; set; }
        public System.DateTime StartAt { get; set; }
        public Nullable<System.DateTime> EndAt { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
        public virtual Race Race { get; set; }
    }
}
